default:
  before_script:
    - env
    - echo "${DOCKERHUB_TOKEN}" | docker login --username "${DOCKERHUB_USER}" --password-stdin

.retry-and-timeout: &retry-and-timeout
  retry:
    max: 2
    when:
    - job_execution_timeout
    - stuck_or_timeout_failure
    - api_failure
    - runner_system_failure
    - script_failure
    - unknown_failure
  timeout: 20 minutes

stages:
- build

arm64:
  <<: *retry-and-timeout
  stage: build
  parallel:
    matrix:
    - ARCH:
      - arm64
      OS:
      - alpine_3
      - deb_10
      - deb_11
      - rhel_8
      - rhel_9
      - ubuntu_20
      - ubuntu_22
  script:
  - cd ${OS}
  - docker build -t pegasus/buildenv:${OS} --push .
  artifacts: {}
  dependencies: []
  tags:
  - ${ARCH}
  - docker-cli

amd64:
  <<: *retry-and-timeout
  stage: build
  parallel:
    matrix:
    - ARCH:
      - amd64
      OS:
      - alpine_3
      - deb_10
      - deb_11
      - rhel_7
      - rhel_8
      - rhel_9
      - ubuntu_18
      - ubuntu_20
      - ubuntu_22
  script:
  - cd ${OS}
  - docker build -t pegasus/buildenv:${OS} --push .
  artifacts: {}
  dependencies: []
  tags:
  - ${ARCH}
  - docker-cli
