default:
  before_script:
    - env
    - echo "${DOCKERHUB_TOKEN}" | docker login --username "${DOCKERHUB_USER}" --password-stdin

.retry-and-timeout: &retry-and-timeout
  retry:
    max: 2
    when:
    - job_execution_timeout
    - stuck_or_timeout_failure
    - api_failure
    - runner_system_failure
    - script_failure
    - unknown_failure
  timeout: 20 minutes

stages:
- build

Pegasus Docker Build Images:
  <<: *retry-and-timeout
  stage: build
  parallel:
    matrix:
    - OS:
      - alpine_3
      - deb_10
      - deb_11
      - deb_12
      #- rhel_7
      - rhel_8
      - rhel_9
      - ubuntu_18
      - ubuntu_20
      - ubuntu_22
      - ubuntu_24
  script:
  - cd ${OS}
  - docker buildx build --builder multiarch-builder --platform linux/amd64,linux/arm64 --tag pegasus/buildenv:${OS} --progress plain --push .
  tags:
  - docker-cli
  - docker-multiarch
